# Generated by Django 5.0.1 on 2024-01-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employedcompanies',
            name='company_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='current_address',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
