# Generated by Django 5.0.1 on 2024-01-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_employedcompanies_company_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedcompanies',
            name='last_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
