# Generated by Django 5.0.1 on 2024-01-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_alter_employedcompanies_last_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employedcompanies',
            name='last_date',
        ),
    ]
